apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: desktop-app-repo-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: desktop-app-repo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: desktop-app-repo:dev

configMapGenerator:
  - name: desktop-app-repo-config
    behavior: merge
    literals:
      - APP_LOG_LEVEL=DEBUG
