name: Benchmark

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**/benchmark/**"

jobs:
  benchmark-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target desktop_app_template_benchmark -j
          ./build/benchmark/desktop_app_template_benchmark

  benchmark-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --all-extras --dev && uv run pytest benchmark --benchmark-only
        working-directory: backend
